# Generated by Django 5.2.16 on 2026-09-15 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_room_classroom_created_by_and_more'),
        ('lessons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-lesson_date', '-created_at'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='curriculum/attachments/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='curriculum/covers/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date_label',
            field=models.CharField(blank=True, help_text='Optional human-readable date label shown to parents.', max_length=60),
        ),
        migrations.AddField(
            model_name='lesson',
            name='memory_verse',
            field=models.TextField(blank=True, default='Memory verse TBA'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published',
            field=models.BooleanField(default=True, help_text='When False the lesson is hidden from parents.'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scripture',
            field=models.CharField(default='Scripture TBA', max_length=200),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.PositiveSmallIntegerField(default=1, help_text='Week number within the year plan (1–53).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(53)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.classroom'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, default='Sunday school curriculum lesson for parents.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('this_week', 'This Week'), ('upcoming', 'Upcoming'), ('completed', 'Completed')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status', 'published'], name='lessons_les_status_728fae_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['year', 'week'], name='lessons_les_year_3d52df_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('classroom', 'year', 'week'), name='unique_lesson_per_classroom_week'),
        ),
    ]
