# Generated by Django 5.2.16 on 2026-09-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_options_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='activity',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lesson',
            name='objective',
            field=models.TextField(blank=True, default=''),
        ),
    ]
