# Generated by Django 5.2.16 on 2026-09-15 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
    ]
