# Generated by Django 5.2.16 on 2026-09-15 18:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_remove_classroom_room_classroom_created_by_and_more'),
        ('organizations', '0002_organizationmembership_alter_organization_options_and_more'),
        ('students', '0003_remove_student_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['profile__first_name', 'profile__last_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster', to='classes.classroom'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, default='Grade 1', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_email',
            field=models.EmailField(blank=True, default='parent@test.com', help_text="Frontend's `parentEmail`.", max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(blank=True, default='+251', help_text='Existing field — kept for backward compatibility.', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='Parent', help_text="Frontend's `parentName`.", max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated')], db_index=True, default='active', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'classroom'], name='students_st_organiz_d221dd_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_d8da85_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['classroom', 'status'], name='students_st_classro_e1b431_idx'),
        ),
    ]
