# Generated by Django 5.2.16 on 2026-09-15 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('organizations', '0002_organizationmembership_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(blank=True, default='Kids & Parents', max_length=150),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='date_label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=True, help_text='When False the event is hidden from parents.'),
        ),
        migrations.AddField(
            model_name='event',
            name='time_label',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='Event published for parents by admin.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Church', max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status', 'published'], name='events_even_organiz_a0685f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', '-start_datetime'], name='events_even_organiz_c71ca8_idx'),
        ),
    ]
