# Generated by Django 5.2.16 on 2026-09-15 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationmembership_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('video', 'Video'), ('song', 'Song'), ('bible_story', 'Bible Story'), ('course', 'Course'), ('picture', 'Picture')], db_index=True, default='video', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('age_group', models.CharField(default='All ages', help_text='e.g. "Ages 5–10", "All ages".', max_length=50)),
                ('duration', models.CharField(default='3:00', help_text='Display string, e.g. "4:20" or "Gallery".', max_length=20)),
                ('source', models.CharField(choices=[('youtube', 'YouTube'), ('gallery', 'Gallery')], db_index=True, default='gallery', max_length=20)),
                ('youtube_id', models.CharField(blank=True, help_text='Extracted YouTube video ID (not the full URL).', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/items/%Y/%m/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/covers/%Y/%m/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('published', models.BooleanField(default=True, help_text='When False the item is hidden from parents.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'kind', 'published'], name='medias_medi_organiz_ac49f1_idx'), models.Index(fields=['organization', '-created_at'], name='medias_medi_organiz_ccd5f1_idx')],
            },
        ),
    ]
