# Generated by Django 5.2.16 on 2026-09-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='uuid',
        ),
    ]
