# Generated by Django 5.2.16 on 2026-08-17 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(default='parent', max_length=150)),
                ('guardian_contact', models.CharField(default='+251', max_length=15)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('graduated', 'Graduated')], max_length=50, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Enrollment date')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churches.church')),
            ],
        ),
    ]
