# Generated by Django 5.2.16 on 2026-09-02 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization Name')),
                ('denomination', models.CharField(blank=True, max_length=200, null=True, verbose_name='Denomination')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='Status')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Approved')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Approved By')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('website', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website')),
                ('pastor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pastor/Lead Minister')),
                ('founded', models.CharField(blank=True, max_length=20, null=True, verbose_name='Founded Year')),
                ('total_members', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Members')),
                ('total_services', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Services')),
                ('service_times', models.JSONField(blank=True, default=dict, help_text="Format: {'sunday': '10:00 AM', 'wednesday': '7:00 PM', 'friday': '6:00 PM'}", null=True, verbose_name='Service Times')),
                ('social_media', models.JSONField(blank=True, default=dict, help_text="Format: {'facebook': 'url', 'instagram': 'url', 'youtube': 'url'}", null=True, verbose_name='Social Media')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Church',
                'verbose_name_plural': 'Churches',
                'db_table': 'churches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='churches_status_d5a9f8_idx'), models.Index(fields=['denomination'], name='churches_denomin_b59f00_idx'), models.Index(fields=['region'], name='churches_region_a95943_idx')],
            },
        ),
    ]
