# Generated by Django 5.2.16 on 2026-09-02 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent / Guardian'), ('student', 'Student'), ('clergy', 'Clergy / Pastor')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='churches_denomin_b59f00_idx',
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='churches_region_a95943_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='organizatio_status_295901_idx',
            old_name='churches_status_d5a9f8_idx',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='founded',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='pastor',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='region',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='service_times',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='total_members',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='total_services',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organization',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('school', 'School'), ('church', 'Church'), ('both', 'School & Church')], default='school', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('normalized_name',), name='unique_active_normalized_org_name'),
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'approved'])), fields=('organization', 'user'), name='unique_active_membership_per_user_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner'), ('status', 'approved')), fields=('organization', 'role'), name='unique_approved_owner_per_org'),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'admin'), ('status', 'approved')), fields=('organization', 'role'), name='unique_approved_admin_per_org'),
        ),
    ]
