# Generated by Django 5.2.16 on 2026-09-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='organization',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employment_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Employment Date'),
        ),
    ]
