# Generated by Django 5.2.16 on 2026-08-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=200, null=True),
        ),
    ]
