# Generated by Django 5.2.16 on 2026-08-24 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0002_church_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['-created_at'], 'verbose_name': 'Church', 'verbose_name_plural': 'Churches'},
        ),
        migrations.AddField(
            model_name='church',
            name='denomination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Denomination'),
        ),
        migrations.AddField(
            model_name='church',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='church',
            name='founded',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Founded Year'),
        ),
        migrations.AddField(
            model_name='church',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='church',
            name='pastor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pastor/Lead Minister'),
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='church',
            name='service_times',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'sunday': '10:00 AM', 'wednesday': '7:00 PM', 'friday': '6:00 PM'}", null=True, verbose_name='Service Times'),
        ),
        migrations.AddField(
            model_name='church',
            name='social_media',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'facebook': 'url', 'instagram': 'url', 'youtube': 'url'}", null=True, verbose_name='Social Media'),
        ),
        migrations.AddField(
            model_name='church',
            name='total_members',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Members'),
        ),
        migrations.AddField(
            model_name='church',
            name='total_services',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Total Services'),
        ),
        migrations.AddField(
            model_name='church',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='church',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='church',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='church',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='church',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Church Name'),
        ),
        migrations.AlterField(
            model_name='church',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='church',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['status'], name='churches_status_d5a9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['denomination'], name='churches_denomin_b59f00_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['region'], name='churches_region_a95943_idx'),
        ),
        migrations.AlterModelTable(
            name='church',
            table='churches',
        ),
    ]
