# Generated by Django 5.2.16 on 2026-08-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churches', '0003_alter_church_options_church_denomination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='church',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='church',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Approved'),
        ),
    ]
