# Generated by Django 5.2.16 on 2026-08-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, verbose_name='Course Name')),
                ('course_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('credit_hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(max_length=150, verbose_name='Discription')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('is_recess_activity', models.BooleanField(default=False)),
                ('min_sessions_per_week', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('max_sessions_per_week', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('requires_double_period', models.BooleanField(blank=True, default=False)),
                ('preferred_days', models.JSONField(blank=True, default=list)),
                ('room_type', models.CharField(blank=True, choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('GYM', 'Gym')], default='CLASSROOM', max_length=50, null=True)),
                ('avoid_last_period', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
