# Generated by Django 5.2.16 on 2026-09-16 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
        ('lessons', '0004_lesson_activity_lesson_materials_lesson_objective'),
        ('students', '0004_alter_student_options_student_age_student_classroom_and_more'),
        ('teachers', '0003_remove_teacher_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], db_index=True, default='present', max_length=20),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['lesson', 'status'], name='attendance__lesson__bbb7ed_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', '-recorded_at'], name='attendance__student_749331_idx'),
        ),
    ]
