# Generated by Django 5.2.16 on 2026-09-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='organization',
        ),
    ]
