# Generated by Django 5.2.16 on 2026-09-15 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_initial'),
        ('organizations', '0002_organizationmembership_alter_organization_options_and_more'),
        ('students', '0003_remove_student_organization'),
        ('teachers', '0003_remove_teacher_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='room',
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Primary grade for this group, e.g. "Grade 3".', max_length=50),
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacher_name',
            field=models.CharField(blank=True, default='', help_text="Display-only teacher name. Used when no Teacher FK is set, mirroring the frontend's free-text 'teacherName' field.", max_length=200),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['organization', 'status'], name='classes_cla_organiz_8e79eb_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['organization', 'name'], name='classes_cla_organiz_1d28a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_class_name_per_organization'),
        ),
    ]
