# Generated by Django 5.2.16 on 2026-09-15 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationmembership_alter_organization_options_and_more'),
        ('users', '0002_profile_is_agreed_to_terms_alter_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organizationmembership'),
        ),
    ]
